version: '3'
services:
  client:
    build:
      context: .
      args: 
        version: '3.0.1'
    volumes:
    - ./nuget_package:/opt/nuget_package
    links:
    - etcd
  etcd:
    image: elcolio/etcd
